### ISSUE TITLE
re:qb-butcher

### ISSUE THREAD

**Issue by killfire179** [RaweRwe/qbcore-jobs#1]
hi I can get the job to work but when i'm collecting the animals it doesn't give me the in my inventory

**Comment by Brave-developments** [comment]
this scripts are broken

**Comment by RaweRwe** [comment]
You need add butcher items to qbcore.

**Comment by RaweRwe** [comment]
If need to help, its a example : [https://github.com/qbcore-framework/qb-core/blob/main/shared/items.lua](url)
